### ISSUE TITLE
Server crashes whenever a Yo-Yo is right-clicked

### ISSUE THREAD

**Issue by nekonoire** [Draylar/gate-of-babylon#44]
Hello! 
On my server, I found that whenever I tried the Yo-yo and right-click on it, the server would crash with a ticking entity error. Crash report indicates that it's due to the Yo-yo. Not sure 100% if its this mod, or if its in conflict with other mods. 

Below is the crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 4/2/21, 11:32 PM
Description: Ticking entity

java.lang.NoSuchMethodError: 'net.minecraft.class_3414 net.minecraft.class_2498.method_10596()'
	at draylar.gateofbabylon.entity.YoyoEntity.method_5773(YoyoEntity.java:106)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:834)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at draylar.gateofbabylon.entity.YoyoEntity.method_5773(YoyoEntity.java:106)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: gateofbabylon:yoyo (draylar.gateofbabylon.entity.YoyoEntity)
	Entity ID: 9244
	Entity Name: entity.gateofbabylon.yoyo
	Entity's Exact location: -54.58, 64.04, 207.00
	Entity's Block location: World: (-55,64,206), Chunk: (at 9,4,14 in -4,12; contains blocks -64,0,192 to -49,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.75, 0.04, 0.66
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 1 total; [class_3222['nekonoire'/8595, l='ServerLevel[ZaWarudo]', x=-55.32, y=64.00, z=206.33]]
	Chunk stats: ServerChunkCache: 2492
	Level dimension: minecraft:overworld
	Level spawn location: World: (59,64,256), Chunk: (at 11,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 40690320 game time, 2619833 day time
	Level name: ZaWarudo
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 84815 (now: false), thunder time: 86894 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:834)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-70-generic
	Java Version: 11.0.10, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 5878121288 bytes (5605 MB) / 6866075648 bytes (6548 MB) up to 12884901888 bytes (12288 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx12288M -Xms2048M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		agape_space: Agape Space Mod 0.0.8
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		anvil_fix: AnvilFix 1.2.1-1.16
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axesareweapons: Axes Are Weapons 1.0
		battletowers: Battle Towers 3.3.3-1.16.4
		beaconoverhaul: Beacon Overhaul 1.3.0+1.16
		betterend: Better End 0.9.1-pre
		betterimpaling: Better Impaling 2.0.2
		betternether: Better Nether 5.0.7
		bettersleepplus: BetterSleepPlus 2.4.0
		biome_locator: Biome Locator 1.1.2
		blame: Blame 1.16.4-2.4.1
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.1.6
		caelus: Caelus API 0.0.15-1.16.4
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		carrier: Carrier 1.7.4
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-api: Cloth API 1.5.47
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.47
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.47
		cloth-utils-v1: Cloth Utils v1 1.5.47
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		crimsonmoon: Crimson Moon 2.0.4-1.16.5
		curioofundying: Curio of Undying 1.1.1-1.16.5
		curios: Curios API 0.0.12-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		dropspread: Drop Spread 1.0
		environmentalcreepers: Environmental Creepers 1.6.1
		fabric: Fabric API 0.32.5+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.5+351679a77d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallingtree: FallingTree 2.10.2
		fatxporbs: Fat Experience Orbs 0.0.9
		ferritecore: FerriteCore 2.0.3
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.8
		gateofbabylon: Gate Of Babylon 1.4.1-1.16.5
		geckolib3: Geckolib 3.0.23
		go-fish: Go Fish 1.2.1-beta-1.16.4
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		headshot: Headshot 1.0.6
		inmis: Inmis 2.1.2-1.16.4
		inventorysorter: Inventory Sorter 1.7.7-1.16
		java: OpenJDK 64-Bit Server VM 11
		krypton: Krypton 0.1.2
		kyrptconfig: Kytpt Config 1.1.6-1.16
		leadvillagers: Lead Villagers 2.1.0+mc1.16.1
		libcd: LibCapableData 3.0.3+1.16.3
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.4
		luckyblocks: Fabricated Lucky Blocks 1.0.0-1.16.5
		magna: Magna 1.4.2-1.16.2
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		minecraft: Minecraft 1.16.5
		moretotems: More Totems 2.7.3
		mtca: More Totems Curios Addon 1.0.0
		omega-config: OmegaConfig 1.0.4
		phosphor: Phosphor 0.7.1+build.11
		reach-entity-attributes: Reach Entity Attributes 1.1.0
		reroll: Reroll 1.2.0-1.16.5
		rftl: Rotten Flesh To Leather 1.0.0
		staffofbuilding: Staff of Building 1.2.5-1.16.5
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		structure-helpers: Structure Helpers 3.0.0
		team_reborn_energy: Energy 0.1.1
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		unforgivingvoid: Unforgiving Void 2.0.0
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
 		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
 		vanillaexcavators: Vanilla Excavators 1.1.0
		waystones: Waystones 1.1.1.1
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		xaeroworldmap: Xaero's World Map 1.12.2
		xp_storage: XP Storage 1.4+1.16.5
	Player Count: 1 / 10; [class_3222['nekonoire'/8595, l='ServerLevel[ZaWarudo]', x=-55.32, y=64.00, z=206.33]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by nekonoire** [comment]
nvm it seems like this was due to me using the 1.4.1 plugin version instead of 1.4.2 version. Updated to the 1.4.2 version and the server is not crashing when right-clicking with the Yoyo.
