### ISSUE TITLE
game crashing when loading with Gate of Babylon 

### ISSUE THREAD

**Issue by xTheEpicGamerx** [Draylar/gate-of-babylon#60]
Im trying to load this mod in 1.17 but the game crashes, it says something is missing but won't actually say what it is, here is the game output: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: gateofbabylon requires {fabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195)

**Comment by xTheEpicGamerx** [comment]
Forgot to put in Fabric API :P
